@echo off
chcp 65001 >nul
title Claude Code
Set CLAUDE_CODE_USE_POWERSHELL_TOOL=1
set CLAUDE_CODE_AUTO_COMPACT_WINDOW=256000
set CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=80
set CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN=1
claude --dangerously-skip-permissions